server:
  port: 8089
spring:
  application:
    name: EduFood
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
  web:
    resources:
      static-locations: classpath:/static/,file:./avatars/

  # ------------- DataBases
  datasource:
    url: jdbc:h2:./db/EduFood;AUTO_SERVER=true
    username: root
    password: 2565
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  h2:
    console:
      enabled: false

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

  file:
    name: logs/spring.log

app:
  user_not_found_with_id: user with id {} not found
  file_dir: files

